//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Der
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Der()
        {
            this.Not_ = new HashSet<Not_>();
            this.DersSecmes = new HashSet<DersSecme>();
        }
    
        public string DersKodu { get; set; }
        public string Yariyil { get; set; }
        public string DersAdi { get; set; }
        public string Dil { get; set; }
        public Nullable<double> Kredi { get; set; }
        public Nullable<double> Akts { get; set; }
        public Nullable<int> BolumID { get; set; }
    
        public virtual Bolum Bolum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Not_> Not_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DersSecme> DersSecmes { get; set; }
    }
}
