//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DersSecme
    {
        public int DersSecID { get; set; }
        public string OgrNo { get; set; }
        public Nullable<int> BolumID { get; set; }
        public string DersKodu { get; set; }
    
        public virtual Bolum Bolum { get; set; }
        public virtual Der Der { get; set; }
        public virtual Ogrenci Ogrenci { get; set; }
    }
}
