//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBS.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ObsDbEntitiessDB : DbContext
    {
        public ObsDbEntitiessDB()
            : base("name=ObsDbEntitiessDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bolum> Bolums { get; set; }
        public virtual DbSet<Der> Ders { get; set; }
        public virtual DbSet<DersSecme> DersSecmes { get; set; }
        public virtual DbSet<Fakulte> Fakultes { get; set; }
        public virtual DbSet<Not_> Not_ { get; set; }
        public virtual DbSet<Ogrenci> Ogrencis { get; set; }
        public virtual DbSet<OgrenciIsleri> OgrenciIsleris { get; set; }
        public virtual DbSet<OgretimElemani> OgretimElemanis { get; set; }
    
        public virtual ObjectResult<akademisyenbilgi_Result> akademisyenbilgi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<akademisyenbilgi_Result>("akademisyenbilgi");
        }
    
        public virtual ObjectResult<Ogrencibil_Result> Ogrencibil()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ogrencibil_Result>("Ogrencibil");
        }
    
        public virtual ObjectResult<secilmisdersler_Result> secilmisdersler()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<secilmisdersler_Result>("secilmisdersler");
        }
    
        public virtual ObjectResult<tbNotlar_Result> tbNotlar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbNotlar_Result>("tbNotlar");
        }
    }
}
