//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OgretimElemani
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OgretimElemani()
        {
            this.Not_ = new HashSet<Not_>();
            this.Ogrencis = new HashSet<Ogrenci>();
        }
    
        public string OgrtID { get; set; }
        public string OgrtAd { get; set; }
        public string OgrtSoyad { get; set; }
        public string Unvan { get; set; }
        public string OgrtMail { get; set; }
        public string OgrtSifre { get; set; }
        public string OgrtYetkiID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Not_> Not_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ogrenci> Ogrencis { get; set; }
    }
}
